[application]
name = "qrmonsters"
default_platform = "mobile"

# Point to the app crate in the workspace
[application.package]
path = "crates/app"

[web.app]
title = "QR Monsters"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
